services:
  user-service:
    build:
      context: ./BackEnd/user-service
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8081:8081"
    networks:
      - app-network

  account-service:
    build:
      context: ./BackEnd/account-service
    container_name: account-service
    depends_on:
      - user-service
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8082:8082"
    networks:
      - app-network

  front-app:
    build:
      context: ./FrontEnd
    container_name: front-app
    depends_on:
      - user-service
      - account-service
    ports:
      - "4200:4200"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
