server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/nttdb
    username: abastidas
    password: nttRodio

user-service:
  url: http://user-service:8081

logging:
  level:
    com.ntt.account_service.client: DEBUG
    feign: DEBUG
